name: Build ExWi

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'Discord.Bots.ExWi/**'
      - 'Discord.Bots.Core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore "./Discord.Bots.ExWi"

    - name: Build
      run: dotnet build "./Discord.Bots.ExWi" --configuration Release --no-restore

    - name: Test
      run: dotnet test "./Discord.Bots.ExWi" --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish "./Discord.Bots.ExWi" -c Release -o release

    - name: Commit to ExWi
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: exwi
        FOLDER: release
