name: Build KGB

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'KGB/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore "./KGB"

    - name: Build
      run: dotnet build "./KGB" --configuration Release --no-restore

    - name: Test
      run: dotnet test "./KGB" --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish "./KGB" -c Release -o release

    - name: Commit to KGB
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: kgb
        FOLDER: release
